vich_uploader:
    db_driver: orm

    mappings:
        restaurant_image:
           uri_prefix: /images/restaurants
           upload_destination: '%kernel.project_dir%/public/img/restaurants'
        
        plat_image:
            uri_prefix: /images/plats
            upload_destination: '%kernel.project_dir%/public/img/plats'
